/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    settings: Setting;
    pages: Page;
    treatments: Treatment;
    'treatment-categories': TreatmentCategory;
    'team-members': TeamMember;
    'practice-pages': PracticePage;
    faq: Faq;
    testimonials: Testimonial;
    'contact-info': ContactInfo;
    'practice-info': PracticeInfo;
    locations: Location;
    'english-page': EnglishPage;
    'children-page': ChildrenPage;
    'careers-page': CareersPage;
    privacy: Privacy;
    'terms-and-conditions': TermsAndCondition;
    alerts: Alert;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    settings: SettingsSelect<false> | SettingsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    treatments: TreatmentsSelect<false> | TreatmentsSelect<true>;
    'treatment-categories': TreatmentCategoriesSelect<false> | TreatmentCategoriesSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    'practice-pages': PracticePagesSelect<false> | PracticePagesSelect<true>;
    faq: FaqSelect<false> | FaqSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'contact-info': ContactInfoSelect<false> | ContactInfoSelect<true>;
    'practice-info': PracticeInfoSelect<false> | PracticeInfoSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    'english-page': EnglishPageSelect<false> | EnglishPageSelect<true>;
    'children-page': ChildrenPageSelect<false> | ChildrenPageSelect<true>;
    'careers-page': CareersPageSelect<false> | CareersPageSelect<true>;
    privacy: PrivacySelect<false> | PrivacySelect<true>;
    'terms-and-conditions': TermsAndConditionsSelect<false> | TermsAndConditionsSelect<true>;
    alerts: AlertsSelect<false> | AlertsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: string;
  name: string;
  slug: string;
  hero: {
    title: string;
    subtitle: string;
    image: string | Media;
  };
  /**
   * Important announcement to display at the top of the homepage
   */
  importantAnnouncement?: {
    /**
     * Enable or disable the announcement
     */
    isActive?: boolean | null;
    /**
     * Title of the announcement (e.g., "BELANGRIJK !!")
     */
    title?: string | null;
    /**
     * Content of the announcement
     */
    content?: string | null;
    /**
     * Background color of the announcement banner
     */
    backgroundColor?: ('accent' | 'primary' | 'secondary' | 'warning') | null;
  };
  /**
   * Social media links for the website
   */
  socialMedia?: {
    /**
     * Facebook URL
     */
    facebook?: string | null;
    /**
     * Instagram URL
     */
    instagram?: string | null;
    /**
     * LinkedIn URL
     */
    linkedin?: string | null;
  };
  contact: {
    email: string;
    phone: string;
    address: string;
  };
  /**
   * Default SEO settings
   */
  seo?: {
    defaultTitle?: string | null;
    defaultDescription?: string | null;
    defaultKeywords?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  /**
   * This is the URL-friendly identifier for the page (e.g., "over-ons" for a page at /over-ons)
   */
  slug: string;
  pageType: 'home' | 'practice' | 'treatments' | 'contact' | 'other';
  /**
   * If this is a subpage, select the parent page
   */
  parentPage?: (string | null) | Page;
  /**
   * Title for SEO purposes. If left blank, the regular title will be used.
   */
  metaTitle?: string | null;
  /**
   * Description for SEO purposes.
   */
  metaDescription?: string | null;
  hero?: {
    heroImage?: (string | null) | Media;
    heroTitle?: string | null;
    heroContent?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  layout?:
    | (
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'content';
          }
        | {
            image: string | Media;
            text: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            imagePosition?: ('left' | 'right') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageText';
          }
        | {
            title: string;
            text?: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            buttonText?: string | null;
            buttonLink?: string | null;
            backgroundColor?: ('primary' | 'secondary' | 'light') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'callToAction';
          }
      )[]
    | null;
  /**
   * Should this page be shown in the main navigation?
   */
  showInNavigation?: boolean | null;
  /**
   * Should this page be shown in the footer navigation?
   */
  showInFooter?: boolean | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "treatments".
 */
export interface Treatment {
  id: string;
  title: string;
  /**
   * This is the URL-friendly identifier for the treatment (e.g., "vullingen" for a page at /behandelingen/vullingen)
   */
  slug: string;
  /**
   * Choose a category for this treatment. Options are loaded from the global treatment categories. If not seeing updated options, try refreshing the page.
   */
  category:
    | 'preventie'
    | 'diagnostiek'
    | 'restauratief'
    | 'endodontologie'
    | 'prothetiek'
    | 'implantologie'
    | 'orthodontie'
    | 'overig';
  featuredImage?: (string | null) | Media;
  shortDescription: string;
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Title for SEO purposes. If left blank, the regular title will be used.
   */
  metaTitle?: string | null;
  /**
   * Description for SEO purposes. If left blank, the short description will be used.
   */
  metaDescription?: string | null;
  /**
   * Order in which to display this treatment in listings (lower numbers appear first).
   */
  displayOrder?: number | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage categories for dental treatments. These categories can be assigned to treatments.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "treatment-categories".
 */
export interface TreatmentCategory {
  id: string;
  /**
   * Unique identifier (e.g., "preventie")
   */
  value: string;
  /**
   * Display name (e.g., "Preventie")
   */
  label: string;
  /**
   * Description of this category of treatments
   */
  description?: string | null;
  /**
   * Order in which to display this category (lower numbers appear first)
   */
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: string;
  name: string;
  /**
   * This is the URL-friendly identifier for the team member
   */
  slug: string;
  /**
   * Job title or role (e.g., "Tandarts", "Mondhygiënist")
   */
  role: string;
  photo: string | Media;
  bio: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Areas of specialization or expertise
   */
  specializations?:
    | {
        specialization: string;
        id?: string | null;
      }[]
    | null;
  education?:
    | {
        degree: string;
        institution: string;
        year?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Days when this team member is available at the practice
   */
  workDays?: ('monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday')[] | null;
  /**
   * Order in which to display this team member (lower numbers appear first)
   */
  displayOrder?: number | null;
  /**
   * Is this team member currently active?
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "practice-pages".
 */
export interface PracticePage {
  id: string;
  title: string;
  /**
   * Unieke URL-slug voor deze pagina (bijv. "over-ons")
   */
  slug: string;
  status: 'published' | 'draft';
  hero?: {
    heroImage?: (string | null) | Media;
    /**
     * Optionele aangepaste titel voor de hero-sectie
     */
    heroTitle?: string | null;
    heroContent?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  content?:
    | (
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'textContent';
          }
        | {
            image: string | Media;
            text: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            imagePosition: 'left' | 'right';
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageWithText';
          }
        | {
            name: string;
            role: string;
            image?: (string | null) | Media;
            bio: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            specialties?:
              | {
                  specialty: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'teamMember';
          }
        | {
            title: string;
            description: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            images?:
              | {
                  image: string | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'facilityHighlight';
          }
      )[]
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  /**
   * Schakel in om deze pagina in de zijbalknavigatie te tonen
   */
  showInNavigation?: boolean | null;
  /**
   * Volgorde in de navigatie (lager = hoger in de lijst)
   */
  navigationOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface Faq {
  id: string;
  title: string;
  faqItems?:
    | {
        question: string;
        answer: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        category: 'general' | 'treatments' | 'insurance' | 'practice';
        homepage?: boolean | null;
        order: number;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: string;
  name: string;
  /**
   * e.g., "Yoga Student", "Workshop Participant"
   */
  role?: string | null;
  content: string;
  rating: number;
  image?: (string | null) | Media;
  featured?: boolean | null;
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-info".
 */
export interface ContactInfo {
  id: string;
  /**
   * This is just a label for the CMS and won't be displayed on the website.
   */
  title: string;
  address: {
    street: string;
    postalCode: string;
    city: string;
    area?: string | null;
  };
  contactDetails: {
    phone: string;
    email: string;
    kvkNumber?: string | null;
    agbCode?: string | null;
  };
  openingHours?:
    | {
        day: 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday';
        /**
         * Format: HH:MM (e.g., 08:00)
         */
        openTime: string;
        /**
         * Format: HH:MM (e.g., 17:00)
         */
        closeTime: string;
        isClosed?: boolean | null;
        id?: string | null;
      }[]
    | null;
  receptionHours?:
    | {
        day: 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday';
        /**
         * Format: HH:MM (e.g., 08:30)
         */
        morningOpen?: string | null;
        /**
         * Format: HH:MM (e.g., 12:00)
         */
        morningClose?: string | null;
        /**
         * Format: HH:MM (e.g., 13:00)
         */
        afternoonOpen?: string | null;
        /**
         * Format: HH:MM (e.g., 16:30)
         */
        afternoonClose?: string | null;
        isClosed?: boolean | null;
        id?: string | null;
      }[]
    | null;
  emergencyInfo?: {
    phone?: string | null;
    alternatePhone?: string | null;
    instructions?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  closedDays?:
    | {
        /**
         * Name of the holiday or closed day (e.g., "Goedevrijdag")
         */
        name: string;
        /**
         * Format: DD-MM-YYYY or description (e.g., "18-04-2025" or "Vrijdag 18 april 2025")
         */
        date: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Google Maps or other map embed code
   */
  mapEmbed?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "practice-info".
 */
export interface PracticeInfo {
  id: string;
  name: string;
  description: string;
  openingHours: string;
  phoneNumber: string;
  address: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: string;
  name: string;
  address: {
    street: string;
    city: string;
    postalCode: string;
  };
  contact: {
    email: string;
    phone: string;
  };
  openingHours?:
    | {
        day: 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday';
        openTime: string;
        closeTime: string;
        id?: string | null;
      }[]
    | null;
  image: string | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "english-page".
 */
export interface EnglishPage {
  id: string;
  title: string;
  subtitle?: string | null;
  heroImage: string | Media;
  intro: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  servicesIntro?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  services?:
    | {
        title: string;
        description: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  insuranceInfo?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  appointmentInfo?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  faq?:
    | {
        question: string;
        answer: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  metaDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "children-page".
 */
export interface ChildrenPage {
  id: string;
  title: string;
  subtitle?: string | null;
  heroImage: string | Media;
  intro: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  ageGroups: {
    title: string;
    ageRange: string;
    description: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    image?: (string | null) | Media;
    id?: string | null;
  }[];
  tips?:
    | {
        title: string;
        description: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        icon?: ('tooth' | 'brush' | 'food' | 'calendar' | 'star') | null;
        id?: string | null;
      }[]
    | null;
  faq?:
    | {
        question: string;
        answer: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  metaDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers-page".
 */
export interface CareersPage {
  id: string;
  title: string;
  subtitle?: string | null;
  heroImage: string | Media;
  intro: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  teamValues?:
    | {
        title: string;
        description: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        icon?: ('heart' | 'star' | 'trophy' | 'users' | 'lightbulb') | null;
        id?: string | null;
      }[]
    | null;
  benefits?:
    | {
        title: string;
        description: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  vacancies?:
    | {
        title: string;
        description: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        isActive?: boolean | null;
        hours: string;
        id?: string | null;
      }[]
    | null;
  contactInfo: {
    email: string;
    phone?: string | null;
    contactPerson?: string | null;
  };
  metaDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Privacybeleid van title
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy".
 */
export interface Privacy {
  id: string;
  title: string;
  /**
   * Datum van laatste update
   */
  lastUpdated: string;
  /**
   * De inhoud van het privacybeleid
   */
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * SEO titel (optioneel)
   */
  metaTitle?: string | null;
  /**
   * SEO beschrijving (optioneel)
   */
  metaDescription?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Algemene voorwaarden van title
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terms-and-conditions".
 */
export interface TermsAndCondition {
  id: string;
  title: string;
  /**
   * Datum van laatste update
   */
  lastUpdated: string;
  /**
   * De inhoud van de algemene voorwaarden
   */
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * SEO titel (optioneel)
   */
  metaTitle?: string | null;
  /**
   * SEO beschrijving (optioneel)
   */
  metaDescription?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "alerts".
 */
export interface Alert {
  id: string;
  /**
   * Internal name for this alert (not displayed to users)
   */
  title: string;
  /**
   * Toggle to show or hide this alert
   */
  isActive?: boolean | null;
  /**
   * Type of alert which determines the color scheme
   */
  alertType: 'info' | 'warning' | 'error' | 'success';
  /**
   * Alert message content
   */
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Where this alert should appear
   */
  position?: ('global' | 'home') | null;
  /**
   * Allow users to dismiss this alert
   */
  dismissible?: boolean | null;
  /**
   * Optional: Date when this alert should automatically deactivate
   */
  expiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'settings';
        value: string | Setting;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'treatments';
        value: string | Treatment;
      } | null)
    | ({
        relationTo: 'treatment-categories';
        value: string | TreatmentCategory;
      } | null)
    | ({
        relationTo: 'team-members';
        value: string | TeamMember;
      } | null)
    | ({
        relationTo: 'practice-pages';
        value: string | PracticePage;
      } | null)
    | ({
        relationTo: 'faq';
        value: string | Faq;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: string | Testimonial;
      } | null)
    | ({
        relationTo: 'contact-info';
        value: string | ContactInfo;
      } | null)
    | ({
        relationTo: 'practice-info';
        value: string | PracticeInfo;
      } | null)
    | ({
        relationTo: 'locations';
        value: string | Location;
      } | null)
    | ({
        relationTo: 'english-page';
        value: string | EnglishPage;
      } | null)
    | ({
        relationTo: 'children-page';
        value: string | ChildrenPage;
      } | null)
    | ({
        relationTo: 'careers-page';
        value: string | CareersPage;
      } | null)
    | ({
        relationTo: 'privacy';
        value: string | Privacy;
      } | null)
    | ({
        relationTo: 'terms-and-conditions';
        value: string | TermsAndCondition;
      } | null)
    | ({
        relationTo: 'alerts';
        value: string | Alert;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  hero?:
    | T
    | {
        title?: T;
        subtitle?: T;
        image?: T;
      };
  importantAnnouncement?:
    | T
    | {
        isActive?: T;
        title?: T;
        content?: T;
        backgroundColor?: T;
      };
  socialMedia?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        linkedin?: T;
      };
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        address?: T;
      };
  seo?:
    | T
    | {
        defaultTitle?: T;
        defaultDescription?: T;
        defaultKeywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  pageType?: T;
  parentPage?: T;
  metaTitle?: T;
  metaDescription?: T;
  hero?:
    | T
    | {
        heroImage?: T;
        heroTitle?: T;
        heroContent?: T;
      };
  layout?:
    | T
    | {
        content?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        imageText?:
          | T
          | {
              image?: T;
              text?: T;
              imagePosition?: T;
              id?: T;
              blockName?: T;
            };
        callToAction?:
          | T
          | {
              title?: T;
              text?: T;
              buttonText?: T;
              buttonLink?: T;
              backgroundColor?: T;
              id?: T;
              blockName?: T;
            };
      };
  showInNavigation?: T;
  showInFooter?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "treatments_select".
 */
export interface TreatmentsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  featuredImage?: T;
  shortDescription?: T;
  content?: T;
  metaTitle?: T;
  metaDescription?: T;
  displayOrder?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "treatment-categories_select".
 */
export interface TreatmentCategoriesSelect<T extends boolean = true> {
  value?: T;
  label?: T;
  description?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  role?: T;
  photo?: T;
  bio?: T;
  specializations?:
    | T
    | {
        specialization?: T;
        id?: T;
      };
  education?:
    | T
    | {
        degree?: T;
        institution?: T;
        year?: T;
        id?: T;
      };
  workDays?: T;
  displayOrder?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "practice-pages_select".
 */
export interface PracticePagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  hero?:
    | T
    | {
        heroImage?: T;
        heroTitle?: T;
        heroContent?: T;
      };
  content?:
    | T
    | {
        textContent?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        imageWithText?:
          | T
          | {
              image?: T;
              text?: T;
              imagePosition?: T;
              id?: T;
              blockName?: T;
            };
        teamMember?:
          | T
          | {
              name?: T;
              role?: T;
              image?: T;
              bio?: T;
              specialties?:
                | T
                | {
                    specialty?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        facilityHighlight?:
          | T
          | {
              title?: T;
              description?: T;
              images?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  showInNavigation?: T;
  navigationOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_select".
 */
export interface FaqSelect<T extends boolean = true> {
  title?: T;
  faqItems?:
    | T
    | {
        question?: T;
        answer?: T;
        category?: T;
        homepage?: T;
        order?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  content?: T;
  rating?: T;
  image?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-info_select".
 */
export interface ContactInfoSelect<T extends boolean = true> {
  title?: T;
  address?:
    | T
    | {
        street?: T;
        postalCode?: T;
        city?: T;
        area?: T;
      };
  contactDetails?:
    | T
    | {
        phone?: T;
        email?: T;
        kvkNumber?: T;
        agbCode?: T;
      };
  openingHours?:
    | T
    | {
        day?: T;
        openTime?: T;
        closeTime?: T;
        isClosed?: T;
        id?: T;
      };
  receptionHours?:
    | T
    | {
        day?: T;
        morningOpen?: T;
        morningClose?: T;
        afternoonOpen?: T;
        afternoonClose?: T;
        isClosed?: T;
        id?: T;
      };
  emergencyInfo?:
    | T
    | {
        phone?: T;
        alternatePhone?: T;
        instructions?: T;
      };
  closedDays?:
    | T
    | {
        name?: T;
        date?: T;
        id?: T;
      };
  mapEmbed?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "practice-info_select".
 */
export interface PracticeInfoSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  openingHours?: T;
  phoneNumber?: T;
  address?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  name?: T;
  address?:
    | T
    | {
        street?: T;
        city?: T;
        postalCode?: T;
      };
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
      };
  openingHours?:
    | T
    | {
        day?: T;
        openTime?: T;
        closeTime?: T;
        id?: T;
      };
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "english-page_select".
 */
export interface EnglishPageSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  heroImage?: T;
  intro?: T;
  servicesIntro?: T;
  services?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  insuranceInfo?: T;
  appointmentInfo?: T;
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "children-page_select".
 */
export interface ChildrenPageSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  heroImage?: T;
  intro?: T;
  ageGroups?:
    | T
    | {
        title?: T;
        ageRange?: T;
        description?: T;
        image?: T;
        id?: T;
      };
  tips?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        id?: T;
      };
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers-page_select".
 */
export interface CareersPageSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  heroImage?: T;
  intro?: T;
  teamValues?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        id?: T;
      };
  benefits?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  vacancies?:
    | T
    | {
        title?: T;
        description?: T;
        isActive?: T;
        hours?: T;
        id?: T;
      };
  contactInfo?:
    | T
    | {
        email?: T;
        phone?: T;
        contactPerson?: T;
      };
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy_select".
 */
export interface PrivacySelect<T extends boolean = true> {
  title?: T;
  lastUpdated?: T;
  content?: T;
  metaTitle?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terms-and-conditions_select".
 */
export interface TermsAndConditionsSelect<T extends boolean = true> {
  title?: T;
  lastUpdated?: T;
  content?: T;
  metaTitle?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "alerts_select".
 */
export interface AlertsSelect<T extends boolean = true> {
  title?: T;
  isActive?: T;
  alertType?: T;
  content?: T;
  position?: T;
  dismissible?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}